# Generated by Django 4.1.5 on 2023-02-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(to='demoapp.project'),
        ),
    ]
