# Generated by Django 4.1.5 on 2023-02-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('joining_date', models.DateField(auto_now=True)),
                ('pointer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email_id', models.EmailField(max_length=250)),
                ('student_pic', models.ImageField(upload_to=None)),
                ('school_students', models.IntegerField()),
            ],
        ),
    ]
