# Generated by Django 4.1.5 on 2023-02-02 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orm_practice', '0002_alter_school_student_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('fees', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='student_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orm_practice.students'),
        ),
    ]
